template: |
  ## Changelog

  {{#each categories}}
  {{#if issues.length}}
  ### {{title}}
  {{#each issues}}
  - {{name}} [{{text}}]({{url}})
  {{/each}}
  {{/if}}
  {{/each}}

categories:
  - title: Breaking Changes 🛠
    label: version:major
  - title: Exciting New Features 🎉
    label: version:minor
  - title: Other Changes
    label: version:patch
